---
title: "Shap evaluation"
author: "Kendra Wyant"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

### Set Up Environment

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true"))
suppressPackageStartupMessages(library(tidyposterior))

path_models <- format_path(str_c("risk2/models/combined"))
path_shared <- format_path(str_c("risk2/data_processed/shared"))
```

## Read in data
```{r}
shaps <- read_rds(here::here(path_models, 
                             "outer_shapsgrp_6_x_5_1_x_5_day_v10_nested_full.rds"))

labels <- read_csv(here::here(path_shared, "lapse_labels_24h_day_gps.csv"),
                   show_col_types = FALSE)

dem <- read_csv(here::here(path_shared, "features_fairness.csv"),
                 show_col_types = FALSE) |>
  select(-ruca1) |> 
  filter(subid %in% labels$subid)
```

## Match `id_obs` to fairness subgroups
```{r}
shap_dem <- labels |> 
  select(id_obs = label_num,
         label = lapse,
         subid) |>
  right_join(shaps, by = c("id_obs")) |> 
  mutate(label = factor(label, levels = c("Lapse", "No lapse"))) |> 
  left_join(dem, by = "subid") |> 
  glimpse()

# nrow(shaps)
# nrow(shap_dem) # should be same as nrow(shaps)
```

## Get top 10 global shaps across sample
```{r}
(shaps_10 <- shaps |> 
  group_by(variable_grp) |>
  summarize(mean_value = mean(abs(value)), .groups = "drop") |> 
  arrange(desc(mean_value)) |> 
  slice_head(n = 10))
```


## Test function for Race/ethnicity
```{r}
fit_shap_feature <- function(feature_name, dem_var) {

  if(dem_var == "race") {
    df <- shap_dem |>
      filter(variable_grp == feature_name, !is.na(race)) |>
      group_by(race, split_num, variable_grp) |>
      summarize(mean_value = mean(abs(value)),
                .groups = "drop") |>
      pivot_wider(names_from = race,
                  values_from = mean_value) |>
      arrange(split_num) |>
      mutate(fold_num = rep(1:5, 6),
             repeat_num = rep(1:6, each = 5)) |>
      select(-split_num)
  }
  
  if(dem_var == "gender") {
    df <- shap_dem |>
      filter(variable_grp == feature_name, !is.na(gender)) |>
      group_by(gender, split_num, variable_grp) |>
      summarize(mean_value = mean(abs(value)),
                .groups = "drop") |>
      pivot_wider(names_from = gender,
                  values_from = mean_value) |>
      arrange(split_num) |>
      mutate(fold_num = rep(1:5, 6),
             repeat_num = rep(1:6, each = 5)) |>
      select(-split_num)
  }
  
  if(dem_var == "orientation") {
    df <- shap_dem |>
      filter(variable_grp == feature_name, !is.na(orientation)) |>
      group_by(orientation, split_num, variable_grp) |>
      summarize(mean_value = mean(abs(value)),
                .groups = "drop") |>
      pivot_wider(names_from = orientation,
                  values_from = mean_value) |>
      arrange(split_num) |>
      mutate(fold_num = rep(1:5, 6),
             repeat_num = rep(1:6, each = 5)) |>
      select(-split_num)
  }
  
  if(dem_var == "geography") {
    df <- shap_dem |>
      filter(variable_grp == feature_name, !is.na(geography)) |>
      group_by(geography, split_num, variable_grp) |>
      summarize(mean_value = mean(abs(value)),
                .groups = "drop") |>
      pivot_wider(names_from = geography,
                  values_from = mean_value) |>
      arrange(split_num) |>
      mutate(fold_num = rep(1:5, 6),
             repeat_num = rep(1:6, each = 5)) |>
      select(-split_num)
  }
  
  if(dem_var == "income") {
    df <- shap_dem |>
      filter(variable_grp == feature_name, !is.na(income)) |>
      group_by(income, split_num, variable_grp) |>
      summarize(mean_value = mean(abs(value)),
                .groups = "drop") |>
      pivot_wider(names_from = income,
                  values_from = mean_value) |>
      arrange(split_num) |>
      mutate(fold_num = rep(1:5, 6),
             repeat_num = rep(1:6, each = 5)) |>
      select(-split_num)
  }
  

  pp <- df |>
    select(-variable_grp) |>
    rename(id = fold_num,
           id2 = repeat_num) |>
    perf_mod(formula = statistic ~ model + (1 | id2/id),
      iter = 8000,
      chains = 4,
      adapt_delta = 0.99,
      family = Gamma())

  pp_tidy <- pp |>
    tidy(seed = 123)

  q <- c(.025, .5, .975)

  pp_tidy |>
    group_by(model) |>
    summarize(
      pp_median = quantile(posterior, probs = q[2]),
      pp_lower  = quantile(posterior, probs = q[1]),
      pp_upper  = quantile(posterior, probs = q[3]),
      .groups = "drop"
    ) 
  
  
  if (dem_var == "race") {
     pp_tidy |>
      mutate(model = factor(model,
                            levels = c("Hispanic and/or not white",
                                       "non-Hispanic White")),
             feature = feature_name) |>
      arrange(model)
  }
  
    if (dem_var == "gender") {
     pp_tidy |>
      mutate(model = factor(model,
                            levels = c("not male",
                                       "male")),
             feature = feature_name) |>
      arrange(model)
    }
  
    if (dem_var == "orientation") {
     pp_tidy |>
      mutate(model = factor(model,
                            levels = c("not heterosexual",
                                       "heterosexual")),
             feature = feature_name) |>
      arrange(model)
    }
  
    if (dem_var == "geography") {
     pp_tidy |>
      mutate(model = factor(model,
                            levels = c("small town/rural",
                                       "urban/suburban")),
             feature = feature_name) |>
      arrange(model)
    }
  
    if (dem_var == "income") {
     pp_tidy |>
      mutate(model = factor(model,
                            levels = c("below poverty",
                                       "above poverty")),
             feature = feature_name) |>
      arrange(model)
  }
 
}
```

Run for all top 10 features
```{r}
set.seed(101)

pp_perf_tibble_race <- shaps_10 |>
  pull(variable_grp) |>
  map_dfr(fit_shap_feature, race)

pp_perf_tibble_gender <- shaps_10 |>
  pull(variable_grp) |>
  map_dfr(fit_shap_feature, "gender")

pp_perf_tibble_orientation <- shaps_10 |>
  pull(variable_grp) |>
  map_dfr(fit_shap_feature, "orientation")

pp_perf_tibble_geography <- shaps_10 |>
  pull(variable_grp) |>
  map_dfr(fit_shap_feature, "geography")

pp_perf_tibble_income <- shaps_10 |>
  pull(variable_grp) |>
  map_dfr(fit_shap_feature, "income")

pp_perf_tibble <- pp_perf_tibble_race |> 
  bind_rows(pp_perf_tibble_gender) |> 
  bind_rows(pp_perf_tibble_orientation) |> 
  bind_rows(pp_perf_tibble_geography) |> 
  bind_rows(pp_perf_tibble_income)

pp_perf_tibble |> 
  write_csv(here::here(path_models, "pp_perf_tibble_shap_fairness.csv"))
```


## Make figure

```{r}
shap_levels <- shaps_10 |> 
  arrange(mean_value) |> 
  pull(variable_grp)

pp_perf_tibble |>
  mutate(model = as.character(model),
         group = case_match(model,
                               "male" ~ "Gender",
                               "not male" ~ "Gender",
                               "non-Hispanic White" ~ "Race",
                               "Hispanic and/or not white" ~ "Race",
                               "below poverty" ~ "Income",
                               "above poverty" ~ "Income",
                               "urban/suburban" ~ "Geography",
                               "small town/rural" ~ "Geography",
                               "heterosexual" ~ "Orientation",
                               "not heterosexual" ~ "Orientation"),
         fairness = if_else(model %in% c("not male", 
                                         "Hispanic and/or not white",
                                         "below poverty",
                                         "small town/rural",
                                         "not heterosexual"), 
                            "Disadvantaged (not male, Hispanic and/or not White, <$25,000 income, rural, not heterosexual)",
                            "Advantaged (male, non-Hispanic White, $25,000+ income, urban, heterosexual)"),
         fairness = factor(fairness),
         group = factor(group, levels = c("Gender", "Race",
                                                "Income", "Orientation", "Geography")),
         feature = factor(feature, levels = shap_levels)) |>  
 ggplot(aes(x = feature, y = pp_median, color = fairness, group = fairness)) +
  geom_point(position = position_dodge(width = 0.5), size = 2) +
  geom_errorbar(aes(ymin = pp_lower, ymax = pp_upper),
                position = position_dodge(width = 0.5), width = 0) +
  facet_wrap(~group) +
  labs(x = NULL,
       y = "Mean(|Shapley Value|)",
       color = NULL) +
  theme_classic() +
  theme(legend.position = "bottom",
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1)) +
  scale_color_manual(values = c("#240e31", "#046B52")) +
  coord_flip() +
  guides(color = guide_legend(nrow = 2, byrow = TRUE))
```


