---
title: "Make GPS filtered" 
author: "Kendra Wyant"
date: "`r lubridate::today()`"
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---


## Notes

This script combines filters down raw gps data `gps.rds`to gps study sample.




## Set up

```{r}
#| include: false
library(tidyverse) 
library(kableExtra, exclude = "group_rows")
library(lubridate)
library(geosphere)

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/fun_gps.R?raw=true")


path_processed <- format_path("risk2/data_processed/shared")
path_raw <- format_path("risk2/", resource = "restricted")
```

## Read in data

Read in data.
```{r}
study_dates <- read_csv(here::here(path_processed, "study_dates_gps.csv"),
                        show_col_types = FALSE)
gps <- read_rds(here::here(path_raw, "data_clean/shared/gps.rds")) |> 
  filter(subid %in% study_dates$subid)
```

# add dist and duration

```{r}
gps <- gps |>
  mutate(longitude = as.numeric(longitude),
         latitude = as.numeric(latitude),
         subid = as.numeric(subid)) |>
  group_by(subid) |>
  arrange(time) |>   # ensure time order
  mutate(dist = distGeo(cbind(longitude, latitude),
                        cbind(lead(longitude), lead(latitude))),
         duration = as.numeric(difftime(lead(time), time, units = "mins")),
         duration = if_else(duration > 5 & dist > 500, NA_real_, duration)) |>
  ungroup()

```


## Save GPS  

```{r}
gps %>% 
  vroom::vroom_write(here::here(path_raw, "data_clean/gps/gps_filtered.csv.xz"), delim = ",")
```


## EDA

```{r}
gps_counts <- gps |> 
  mutate(date = date(time)) |> 
  group_by(subid, date) |> 
  count()


gps_counts |> 
  ggplot(aes(x = n)) +
  geom_histogram(bins = 50) +
  theme_classic()

gps_counts |> 
  filter(n < 1000) |> 
  ggplot(aes(x = n)) +
  geom_histogram(bins = 50) +
  theme_classic()

gps_counts |> 
  filter(n < 100) |> 
  ggplot(aes(x = n)) +
  geom_histogram(bins = 50) +
  theme_classic()


gps_counts |> 
  filter(n < 50) |> 
  ggplot(aes(x = n)) +
  geom_histogram(bins = 50) +
  theme_classic()
```

Use 25 points per day as cut? 18 subids would be removed
```{r}
gps_subid <- gps |> 
  group_by(subid) |> 
  count()

gps_subid <- gps_subid |> 
  left_join(study_dates |> 
              mutate(days_on_study = as.numeric(date(ema_end) - study_start)) |> 
              select(subid, days_on_study), by = "subid") |> 
  mutate(gps_per_day = n/days_on_study)

gps_subid |> 
  filter(gps_per_day < 25) |> 
  nrow()

gps_subid |> 
  filter(gps_per_day < 25) |> 
  pull(subid)
```

