---
title: "Calculate auROC for first vs not-first lapses"
author: "Kendra Wyant"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
params:
  
  study: "combined"
  model: "dyn" 
  version: "v7"
editor_options: 
  chunk_output_type: console
---

### Set Up Environment

```{r}
study <- params$study
model <- params$model
version <- params$version
```


Packages, functions, and paths
```{r}
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)
options(conflicts.policy = "depends.ok")

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

path_shared <- format_path(str_c("risk2/data_processed/shared"))
path_models <- format_path(str_c("risk2/models/", study))
```


### Data

```{r}
preds <- read_rds(here::here(path_models, str_c("preds_xgboost_kfold_6_x_5_", version, 
                                                "_", model, ".rds")))

labels <- read_csv(here::here(path_shared, "lapse_labels_1day_gps.csv"),
                   show_col_types = FALSE)
```


### Create first lapse data frame

```{r}
first_lapses <- labels |> 
  filter(lapse == "Lapse") |> 
  group_by(subid) |> 
  arrange(window_start) |> 
  slice_head(n = 1)
```


### Combine data

```{r}
preds_combined <- labels |> 
  mutate(first_lapse = if_else(label_num %in% first_lapses$label_num, "Yes", "No")) |> 
  select(id_obs = label_num,
         label = lapse,
         subid,
         first_lapse) |>
  right_join(preds, by = c("id_obs", "label")) |> 
  mutate(label = factor(label, levels = c("Lapse", "No lapse")))

# nrow(first_lapses)
# preds_combined |> filter(first_lapse == "Yes") |> nrow() |>  unique()

# nrow(preds)
# nrow(preds_combined) # should be same as nrow(preds)
```


### Calculate average probabilities by group

```{r}
preds_combined |> 
  filter(label == "Lapse") |> 
  group_by(first_lapse) |> 
  summarise(mean(prob_raw),
            median(prob_raw),
            min(prob_raw),
            max(prob_raw))

preds_combined |> 
  filter(label == "No lapse") |> 
  summarise(mean(prob_raw),
            median(prob_raw),
            min(prob_raw),
            max(prob_raw))
```

