---
title: "Make Figures"
author: "Kendra Wyant"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
format:
  html:
    embed-resources: true
params:
  
  study: "combined"
  model: "dyn_dem_oud" 
  version: "v7"
editor_options: 
  chunk_output_type: console
---


```{r}
#| include: false
study <- params$study
model <- params$model
version <- params$version
```


```{r}
#| include: false
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)
library(patchwork)

devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")

path_shared <- format_path(str_c("risk2/data_processed/shared"))
path_models <- format_path(str_c("risk2/models/", study))


pp_all <- read_csv(here::here(path_models, 
                              "pp_perf_tibble_xgboost_v7.csv"),
                   show_col_types = FALSE) 

pp_dem <- read_csv(here::here(path_models, 
                              "pp_fairness_xgboost_full.csv"),
                   show_col_types = FALSE)
preds <- read_rds(here::here(path_models, "preds_xgboost_kfold_6_x_5_v7_dyn_dem_oud.rds"))

shaps <- read_rds(here::here(path_models, str_c("shapsgrp_xgboost_kfold_6_x_5_",
                                           version, "_", model, ".rds")))
```



### Fairness

```{r}
#| label: fig-1
#| fig-cap: "Posterior probabilities for area under the receiver operating curve (auROC) by demographic subgroup. auROC ranges from .5 (chance performance) to 1 (perfect performance). Subgroups advantaged in access to substance use treatment and outcomes (male, non-Hispanic White, above poverty, urban or surburban geographic location, and some college education) are depicted in dark purple. Subgroups disadvantaged in access to substance use treatment and outcomes (not male, Hispanic and/or not White, below poverty, small town or rural geographic location, and high school education or less) are depicted in green. Overall model performance across groups is depicted as the dashed grey line."
#| message: false
#| code-fold: true

pp_dem |>
  mutate(group = case_match(model,
                               "male" ~ "Gender",
                               "not male" ~ "Gender",
                               "non-Hispanic White" ~ "Race",
                               "Hispanic and/or not white" ~ "Race",
                               "below poverty" ~ "Income",
                               "above poverty" ~ "Income",
                               "urban/suburban" ~ "Geography",
                               "small town/rural" ~ "Geography",
                               "some college" ~ "Education",
                               "high school or less" ~ "Education"),
         fairness = if_else(model %in% c("not male", 
                                         "Hispanic and/or not white",
                                         "below poverty",
                                         "small town/rural",
                                         "high school or less"), 
                            "Disadvantaged (not male, Hispanic and/or not White, below poverty, small town/rural, high school or less)",
                            "Advantaged (male, non-Hispanic White, above poverty, urban/suburban, some college)"),
         fairness = factor(fairness),
         group = factor(group, levels = c("Gender", "Race",
                                                "Income", "Geography", "Education"))) |>  
  ggplot(aes(x = group, y = pp_median, color = fairness)) + 
  geom_point(position = position_dodge(width = 0.5), size = 1) +
  geom_line(position = position_dodge(width = 0.5)) +
  geom_segment(mapping = aes(x = group, y = pp_lower, yend = pp_upper, color = fairness),
               position = position_dodge(width = 0.5)) +
  scale_y_continuous("auROC", limits = c(.50, 1.0)) +
  labs(x = NULL,
       color = NULL) +
  theme_classic() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 7),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1)) +
  scale_color_manual(values = c("#240e31", "#046B52")) +
  geom_hline(yintercept = subset(pp_all, model == "main")$pp_median, linetype = "dashed",  color = "grey") +
guides(color = guide_legend(nrow = 2, byrow = TRUE))

```


### Calibration

```{r}
#| echo: false

bin_width = 0.10

preds_all_logi <- preds |> 
  mutate(bins = cut(prob_logi, breaks = seq(0, 1, bin_width)), 
         lapse = if_else(label == "Lapse", 1, 0),
         prob = "Platt calibration")  

preds_all_raw <- preds |> 
  mutate(bins = cut(prob_raw, breaks = seq(0, 1, bin_width)), 
         lapse = if_else(label == "Lapse", 1, 0),
         prob = "Raw (uncalibrated)") 

rug_data <- preds_all_raw |> 
  mutate(
    bins = as.numeric(bins),
    rug_center = bin_width/2 + bin_width * (bins - 1),
    rug_x = rug_center + runif(n(), -bin_width/2, bin_width/2)
  )
```


```{r}
#| label: fig-2
#| fig-cap: "Calibration plots of raw and calibrated lapse probabilities. Predicted probabilities (x-axis) are binned into deciles. Observed lapse probability (y-axis) represents the proportion of actual lapses observed in each bin. The dashed diagonal represents perfect calibration. Points below the line indicate overestimation and points above the line indicate underestimation. Raw probabilities are depicted as dark purple lines Platt calibrated probabilities are depicted as green dashed lines."

preds_all_raw |> 
  bind_rows(preds_all_logi) |> 
  mutate(prob = factor(prob, levels = c("Raw (uncalibrated)", 
                                        "Platt calibration"))) |> 
  group_by(bins,  prob)  |> 
  summarize(mean_lapse = mean(lapse),
            .groups = "drop") |> 
  mutate(
    bins = as.numeric(bins),
    midpoints = bin_width/2 + bin_width * (bins - 1)
  )  |> 
  ggplot(aes(x = midpoints, y = mean_lapse, group = prob,
             color = prob, linetype = prob)) +
  geom_abline(slope = 1, intercept = 0, linetype = "longdash", color = "gray80") +
  geom_line(linewidth = .7) +
  labs(
    x = "Predicted Lapse Probability (Bin Midpoint)",
    y = "Observed Lapse Probability",
    color = NULL,
    linetype = NULL
  ) +
  geom_rug(data = rug_data, aes(x = rug_x), sides = "b", alpha = 0.3,
           inherit.aes = FALSE) +
  scale_x_continuous(breaks = seq(0, 1, bin_width), limits = c(0, 1)) +
  scale_y_continuous(limits = c(-0.08, 1), breaks = seq(0,1, bin_width),
                     expand = c(0, 0)) +
  coord_cartesian(clip = "off") +
  scale_color_manual(values = c("#240e31", "#046B52")) +
  scale_linetype_manual(values = c("solid", "twodash")) +
  theme_classic(base_size = 11) +
  theme(
    legend.position = "bottom",
    strip.text = element_text(size = 11),
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 10),
    axis.text = element_text(size = 10),
    axis.title = element_text(face = "bold")
  )
```



### Feature Importance

top 30
```{r}
#| code-fold: true

shap_levels <- shaps |> 
  group_by(variable_grp) |>
  summarize(mean_value = mean(abs(value)), .groups = "drop") |> 
  arrange(desc(mean_value)) |> 
  slice_head(n = 30) |> 
  arrange(mean_value) |> 
  pull(variable_grp)

n_obs <- max(shaps$id_obs)

shaps_day_max <- shaps |>
  group_by(id_obs) |>
  slice_max(value) |> 
  group_by(variable_grp) |> 
  summarise(n = n(),
            prop = n/n_obs) |> 
  ungroup() 


global_panel <- shaps |>
  group_by(variable_grp) |>
  summarize(mean_value = mean(abs(value)), .groups = "drop") |> 
  filter(variable_grp %in% shap_levels) |> 
  mutate(variable_grp = factor(variable_grp, levels = shap_levels)) |> 
  ggplot(mapping = aes(x = variable_grp, y = mean_value)) +
  geom_bar(fill = "#240e31", 
           stat = "identity", position = "dodge") +
  labs(y = "Mean(|Shapley Value|)",
       x = NULL,
       fill = NULL) +
  theme_classic() +
  theme(axis.text=element_text(size=9.5),
        legend.key.size = unit(0.25, "cm"),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
        legend.position = "right") +
  coord_flip()


local_panel <- shaps_day_max |> 
  filter(variable_grp %in% shap_levels) |>
  mutate(variable_grp = factor(variable_grp, levels = shap_levels)) |>
  ggplot(mapping = aes(x = variable_grp, y = prop)) +
  geom_bar(fill = "#046B52", 
           stat = "identity", position = "dodge") +
  labs(y = "Proportion of days as top feature",
       x = NULL,
       fill = NULL) +
  theme_classic() +
  theme(axis.text=element_text(size=9.5),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.key.size = unit(0.25, "cm"),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
        legend.position = "right") +
  coord_flip()
```


```{r}
#| label: fig-3
#| fig-width: 8

global_panel + local_panel
```


Supplemental figure with all feature groups
```{r}
#| code-fold: true

shap_levels_all <- shaps |> 
  group_by(variable_grp) |>
  summarize(mean_value = mean(abs(value)), .groups = "drop") |>
  arrange(mean_value) |> 
  pull(variable_grp)


global_panel_all <- shaps |>
  group_by(variable_grp) |>
  summarize(mean_value = mean(abs(value)), .groups = "drop") |> 
  mutate(variable_grp = factor(variable_grp, levels = shap_levels_all)) |> 
  ggplot(mapping = aes(x = variable_grp, y = mean_value)) +
  geom_bar(fill = "#240e31", 
           stat = "identity", position = "dodge") +
  labs(y = "Mean(|Shapley Value|)",
       x = NULL,
       fill = NULL) +
  theme_classic() +
  theme(axis.text=element_text(size=9.5),
        legend.key.size = unit(0.25, "cm"),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
        legend.position = "right") +
  coord_flip()


local_panel_all <- shaps_day_max |> 
  right_join(shaps |> ungroup() |> select(variable_grp) |> distinct(), 
             by = "variable_grp") |> 
  mutate(prop = if_else(is.na(prop), 0, prop)) |> 
  mutate(variable_grp = factor(variable_grp, levels = shap_levels_all)) |>
  ggplot(mapping = aes(x = variable_grp, y = prop)) +
  geom_bar(fill = "#046B52", 
           stat = "identity", position = "dodge") +
  labs(y = "Proportion of days as top feature",
       x = NULL,
       fill = NULL) +
  theme_classic() +
  theme(axis.text=element_text(size=9.5),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.key.size = unit(0.25, "cm"),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
        legend.position = "right") +
  coord_flip()
```


```{r}
#| echo: false
#| fig-width: 8
#| fig-height: 10

global_panel_all + local_panel_all
```

Individual Shapley plots (about 90 categories total)
```{r}
#| label: fig-4
#| fig-cap: "Feature importance partial dependence plots."
#| message: false
#| fig-width: 10
#| fig-height: 14
#| code-fold: true

shap_levels <- shaps |> 
  group_by(variable_grp) |>
  summarize(mean_value = mean(abs(value)), .groups = "drop") |>
  arrange(desc(mean_value)) |> 
  slice_head(n = 30) |> 
  pull(variable_grp)

shaps|>
  filter(variable_grp %in% shap_levels) |>
  mutate(variable_grp = factor(variable_grp, levels = shap_levels)) |>
  ggplot(aes(x = rfvalue, y = value)) +
  geom_point(alpha = .3) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 10, bs = "cs"), se = FALSE) +
  facet_wrap(~ variable_grp, scales = "free", ncol = 5) +
  labs(
    title = "Top 30 SHAP Variable Relationships",
    x = "z-score raw feature score",
    y = "Shapley value"
  ) +
  theme_classic() +
  theme(
    strip.text = element_text(size = 8),
    plot.title = element_text(size = 14, face = "bold")
  )
```


Individual Shapley plots by raw and diff
```{r}
#| label: fig-5
#| fig-cap: "Raw feature importance partial dependence plots."
#| message: false
#| fig-width: 10
#| fig-height: 14
#| code-fold: true

shap_levels <- shaps |> 
  filter(str_detect(variable_grp, "Raw") | str_detect(variable_grp, "demographic")) |> 
  group_by(variable_grp) |>
  summarize(mean_value = mean(abs(value)), .groups = "drop") |>
  arrange(desc(mean_value)) |> 
  pull(variable_grp)

shaps|>
  filter(variable_grp %in% shap_levels) |>
  mutate(variable_grp = factor(variable_grp, levels = shap_levels)) |>
  ggplot(aes(x = rfvalue, y = value)) +
  geom_point(alpha = .3) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5, bs = "cs"), se = FALSE) +
  facet_wrap(~ variable_grp, scales = "free", ncol = 5) +
  labs(
    title = "Raw SHAP Variable Relationships",
    x = "z-score raw feature score",
    y = "Shapley value"
  ) +
  theme_classic() +
  theme(
    strip.text = element_text(size = 8),
    plot.title = element_text(size = 14, face = "bold")
  )
```

```{r}
#| label: fig-6
#| fig-cap: "Difference feature importance partial dependence plots."
#| message: false
#| fig-width: 10
#| fig-height: 14
#| code-fold: true

shap_levels <- shaps |> 
  filter(str_detect(variable_grp, "Diff")) |> 
  group_by(variable_grp) |>
  summarize(mean_value = mean(abs(value)), .groups = "drop") |>
  arrange(desc(mean_value)) |> 
  pull(variable_grp)

shaps|>
  filter(variable_grp %in% shap_levels) |>
  mutate(variable_grp = factor(variable_grp, levels = shap_levels)) |>
  ggplot(aes(x = rfvalue, y = value)) +
  geom_point(alpha = .3) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5, bs = "cs"), se = FALSE) +
  facet_wrap(~ variable_grp, scales = "free", ncol = 5) +
  labs(
    title = "Difference SHAP Variable Relationships",
    x = "z-score raw feature score",
    y = "Shapley value"
  ) +
  theme_classic() +
  theme(
    strip.text = element_text(size = 8),
    plot.title = element_text(size = 14, face = "bold")
  )
```



<!-- ## Tune GAM line -->

<!-- - Thin Plate Regression Splines (bs = "tp") is default and usually best for continuous predictors. -->
<!-- - Rule of thumb: k = min(20, length(unique(x))/4). -->

<!-- ```{r} -->

<!-- min(20, length(unique(subset(shaps, variable_grp == "Urge, Raw (EMA)")$rfvalue))/4) -->


<!-- shaps|> -->
<!--   filter(variable_grp == "Urge, Raw (EMA)") |> -->
<!--   ggplot(aes(x = rfvalue, y = value)) + -->
<!--   geom_point(alpha = .3) + -->
<!--   geom_smooth(method = "gam", formula = y ~ s(x, k = 20, bs = "cs"), se = FALSE) + -->
<!--   labs( -->
<!--     x = "z-score raw feature score", -->
<!--     y = "Shapley value" -->
<!--   ) + -->
<!--   theme_classic()  -->

<!-- ``` -->




<!-- ```{r} -->
<!-- shaps|> -->
<!--   filter(variable_grp == "past_month_opioid_use_yes") |> -->
<!--   ggplot(aes(x = rfvalue, y = value)) + -->
<!--   geom_point(alpha = .3) + -->
<!--   geom_smooth(method = "gam", formula = y ~ s(x, k = 5, bs = "cs"), se = FALSE) + -->
<!--   labs( -->
<!--     x = "z-score raw feature score", -->
<!--     y = "Shapley value" -->
<!--   ) + -->
<!--   theme_classic()  -->

<!-- ``` -->




<!-- ```{r} -->
<!-- library(mgcv) -->

<!-- df <- shaps|> -->
<!--   filter(variable_grp == "Urge, Raw (EMA)")  -->


<!-- # Quick sanity checks -->
<!-- summary(df$rfvalue) -->
<!-- summary(df$value) -->
<!-- sum(is.na(df$rfvalue) | is.na(df$value)) -->


<!-- # Baseline: thin plate regression spline, REML smoothing selection -->
<!-- m1 <- gam( -->
<!--   value ~ s(rfvalue, bs = "tp", k = 200),   -->
<!--   data = df, -->
<!--   method = "REML", -->
<!--   select = TRUE,  # enable shrinkage: removes unnecessary wiggles -->
<!--   gamma = 1.3     # extra penalty discourages overfitting; try 1.2–1.6 -->
<!-- ) -->

<!-- summary(m1) -->
<!-- gam.check(m1)   # checks k adequacy & residuals -->

<!-- ``` -->

<!-- summary(m1): Look at edf (effective degrees of freedom) for s(x) → if edf is close to 1, trend is nearly linear; higher edf means more curvature. -->

<!-- gam.check(m1): If the k-index is < ~1.05 with small p‑value, k may be too small → increase k (e.g., 30–40). If diagnostics look fine but the curve is too wiggly, either reduce k or increase gamma. -->



