---
title: Using smartphone sensing and machine learning for personalized daily lapse risk prediction in a national sample of people with opioid use disorder
author:
  - name: Kendra Wyant 
    corresponding: false
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison
  - name: John J. Curtin 
    corresponding: true
    email: jjcurtin@wisc.edu
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison 
financial-support: This research was supported by a grant from the National Institute on Drug Abuse (NIDA; R01 DA047315 to John J. Curtin).
keywords:
  - Substance use disorders
  - Precision mental health 
abstract: |
  Enter abstract here. 
date: last-modified
number-sections: false 
editor_options: 
  chunk_output_type: console
format:
  html: default
  docx: default
  apaish-typst: 
    documentmode: man
citeproc: true
bibliography: references.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
---

```{r}
#| echo: false
#| message: false

library(tidyverse)
# suppressPackageStartupMessages(source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true"))
# 
# path_models <- format_path(str_c("risk2/models/combined"))

path_models <- "S:/risk2/models/combined"

pp_perf <- read_csv(here::here(path_models, "pp_perf_tibble_v10.csv"),
                    show_col_types = FALSE) 

probs <- read_rds(here::here(path_models, "preds_1_x_5_day_v10_kfold_full_final.rds"))
```

# Introduction

About 4.5 million adults in the United States met criteria for opioid use disorder (OUD) in 2024 [@substanceabuseandmentalhealthservicesadministration2024NSDUHDetailed]. OUD is associated with increased rates of mortality and morbidity, including infectious disease, psychiatric comorbidity, and disability [@hserHighMortalityPatients2017]. The societal burden of untreated OUD is substantial. The combined economic costs of lost productivity, health care expenditures, criminal justice involvement, loss of life, and reduced quality of life have been estimated to exceed $1 trillion [@florenceEconomicBurdenOpioid2021].

Medications for opioid use disorder (MOUD), including methadone and buprenorphine, are effective at reducing opioid use, craving, and overdose risk [@maEffectsMedicationassistedTreatment2019]. They are also associated with improvements in mental health and social functioning, particularly when maintained over extended periods. However, despite strong evidence for MOUD, access remains limited. 

Even among individuals retained in treatment, lapses are frequent and confer a critical period of risk for treatment dropout, relapse, and overdose [@weinsteinLongtermRetentionOffice2017; @heinzLongitudinalObservationalStudy2025]. Opioid lapses are particularly high-risk events. Reduced opioid tolerance (e.g., after a period of abstinence) and the increasing prevalence of fentanyl and other synthetic opioids in the drug supply substantially increase the likelihood of fatal overdose. 

Identifying vulnerable periods of high lapse risk and contextualizing that risk (i.e., *Why* risk is high) could enable individuals to take proactive action to prevent lapse. However, the risk factors that precipitate lapses are highly individualized, numerous, dynamic, and interactive. The optimal supports to address these risks vary both across individuals and within individuals over time. Thus, effective interventions must be personalized to both the individual and the moment to meet the complex and changing needs of people in recovery.

Advances in smartphone sensing methods, including brief daily self-report surveys and passive geolocation sensing, offer a powerful way to collect densely sampled risk-relevant data [@mohrPersonalSensingUnderstanding2017]. These data can be used as inputs into machine learning models to generate temporally precise predictions of lapse risk [@wyantMachineLearningModels2024; @heinzLongitudinalObservationalStudy2025]. Methods from interpretable machine learning can be used to identify personalized predictors of risk at any moment in time [@molnarInterpretableMachineLearning2022]. 

Daily self-report surveys can reliably collect proximal risk factors for lapse, such as recent craving, abstinence self-efficacy, risky situations, and substance use behaviors. Research suggests that individuals can adhere to self-report sensing methods while using substances [@wyantAcceptabilityPersonalSensing2023; @jonesComplianceEcologicalMomentary2019]. However, it is less clear to what extent people in recovery from illicit substance use disorders can, or are willing to, report risk information accurately enough to develop prediction models. People with SUDs may experience greater instability in their day-to-day lives (e.g., stigma or legal consequences may make access to healthcare, stable housing, or supportive relationships more difficult). This instability could make it difficult to recall and report recent behaviors and events promptly or accurately. It may also skew baseline perceptions of what constitutes a risky or stressful experience.

Supplementing self-report data with passively sensed geolocation data could make up for imprecise reports of risk factors or be used for lapse prediction during periods of non-adherence to self-report surveys. Moreover, geolocation data could provide a complementary and distinct set of intervenable features. For example, geolocation data may provide insight into time spent in risky locations or changes in routine (e.g., job loss) that may indicate life stressors. These features may become even more powerful when combined with contextual information from public sources (e.g., census data, alcohol outlet density) or from self-report (e.g., self-evaluated riskiness of specific locations). Geolocation data have been demonstrated to contain sufficient signal for predicting craving [@epsteinPredictionStressDrug2020], a putative precursor to opioid lapse, and therefore represent a promising sensing method for predicting lapse risk.

In the current study, we developed a machine learning model that predicts next-day opioid lapse risk using daily self-report and geolocation sensing data. Our study has several notable strengths. First, we recruited a national sample of participants across the United States who were diverse in regard to race and ethnicity, income, gender, sexual orientation, and geographic location. Second, participants provided sensing data and opioid lapse reports for up to one year, a duration that exceeds previously published SUD prediction studies and allowed us to capture longer-term recovery trajectories. Third, our sample consisted of patients in early recovery from OUD receiving MOUD, ensuring that the study population closely reflected the intended clinical audience for our model. Fourth, we explicitly evaluated model performance across demographic subgroups to assess algorithmic fairness. Finally, we identified the most influential predictors using two complementary quantitative approaches, providing insight into the features that drive lapse risk predictions.

# Methods

## Transparency and Openness
We adhere to research transparency principles that are crucial for robust and replicable science. First, we published this study's protocol as a registered report (International Registered Report Identifier [IRRID]: DERR1-10.2196/29563) during the initial enrollment of pilot participants [@moshontzProspectivePredictionLapses2021]. Second, we followed the Transparent Reporting of a multivariable prediction model for Individual Prognosis Or Diagnosis extension for Artificial Intelligence (TRIPOD+AI) guidelines [@collinsTRIPODAIStatementUpdated2024]. A TRIPOD+AI checklist is available in the supplement.<!--add checklist--> Finally, our features, labels, questionnaires, and other study materials are publicly available on our OSF page ([https://osf.io/zvm7s/overview](https://osf.io/zvm7s/overview)) and our annotated analysis scripts and results are publicly available on our study website ([https://jjcurtin.github.io/study_risk2/](https://jjcurtin.github.io/study_risk2/)).
<!--JJC: Data??--><!--NIH sharing?-->

## Participants
We recruited participants in early recovery from opioid use disorder from across the United States. We recruited through national digital advertising and collaborations with treatment providers at MOUD clinics. Our recruitment strategy was designed to create a diverse sample with respect to demographics (gender, age, race, and ethnicity), and geographic location (urban and rural). We required participants:

- were age 18 or older,
- could read, write, and speak in English,
- were enrolled in and adherent with an MOUD program for at least 1 month but no longer than 12 months or enrolled in or recently completed a day treatment program, and
- had an Android smartphone with an active data plan.  

We did not exclude participants for comorbid substance use or other psychiatric disorders. 

## Procedure
Participants completed three video or phone visits over approximately 12 months. During the enrollment visit, study staff obtained written informed consent and collected demographic information. They walked participants through how to download the Smart Technology for Addiction Recovery (STAR) study app, provided a set of video tutorials to learn how to use the app, and instructed participants to complete the intake survey within the app. The STAR app was developed by the UW Madison Center for Health Enhancement Systems Studies and used for all data collection. Within the app participants could control their data sharing options, monitor completed study tasks, receive reminder notifications about tasks, message staff, and access STAR's suite of resources and tools for people in recovery from AUD [@gustafsonSmartphoneApplicationSupport2014]. Enrolled participants met with study staff one week later to troubleshoot technical issues. At the end of the study enrollment period participants met briefly with study staff for a debriefing session. While on study, participants were expected to complete daily surveys, monthly surveys, and share geolocation sensing data. Other sensing data streams (i.e., daily video check-ins, cellular communications, and app usage data) were collected as part of the parent grant's aims (NIDA R01 DA047315). All procedures were approved by the University of Wisconsin-Madison Institutional Review Board (Study #2019-0656). 

Participants were compensated \$40 for completing the enrollment visit and watching the STAR video tutorials and \$10 for the two follow-up phone visits. Participants were compensated \$10 per month for the monthly survey, up to \$15 per month for the daily surveys^[\$0.25 per survey plus an additional \$3.70 for completing at least 12 surveys in the first half of the month and an additional \$3.70 for completing at least 12 surveys in the second half of the month (total range of \$14.40 - \$15.15)], and \$5 per month for sharing geolocation data.^[Participants were also compensated for providing other sensing data as part of the parent grant's aims, including \$10 per month for sharing cellular communication logs and text message content and up to \$10 per month for the daily video check-in.] Participants were also paid \$50 per month to offset the cost of maintaining a cellphone data plan. 


## Measures

### Individual Differences
We collected self-report information about demographics (age, gender, sexual orientation, race, ethnicity, education, employment, and income). Zip codes from participants' reported home addresses were linked to Rural–Urban Commuting Area (RUCA) codes to characterize the rural–urban status of their residences [@economicresearchserviceusdepartmentofagricultureRuralUrbanCommutingArea]. These variables were collected to characterize our sample. They were also included as features in our model to allow for potential interactions with the sensing features and control for demographic differences on lapse risk. Demographic variables with some evidence for influencing OUD treatment access and clinical outcomes and/or carrying general societal stigma (gender, race/ethnicity, income, sexual orientation, and geographic location) were used to perform subgroup analyses for evaluating model fairness [@pinedoCurrentReexaminationRacial2019; @kilaruIncidenceTreatmentOpioid2020; @olfsonHealthcareCoverageService2022; @greenfieldSubstanceAbuseTreatment2007; @martinNeedReceiptSubstance2022; @lofaroRuralUrbanDifferences2025; @xinExploringIntersectionalityStigma2023]. 

We collected information about OUD history to characterize OUD severity and recovery stability across our sample. These measures included self-reported Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition OUD symptoms [@americanpsychiatricassociationDiagnosticStatisticalManual2022], past month opioid use, past month residential treatment for OUD, past month receipt of psychiatric medication, preferred opioid, preferred route of administration, and lifetime history of overdose. As part of the aims of the parent project, we collected many other trait and state measures throughout the study. A complete list of all measures can be found in our registered report [@moshontzProspectivePredictionLapses2021].


### Daily Survey
Participants completed a brief (1-2 minute) 16-item daily survey each day on study through the STAR app. The daily survey became available in the app at 5:00 AM CST each morning and participants had 24 hours to complete it. Participants could enable push notifications for reminder prompts to complete the survey. Participants reported opioid lapses on the first daily survey item. If participants responded "yes" to the question "Have you used any opioids for non-medical reasons that you have not yet reported?", they were prompted to select the day(s) and time(s) of the lapse(s). Times were reported in 6-hour increments (12:00am–5:59am, 6:00am–11:59am, 12:00pm–5:59pm, 6:00pm–11:59pm). These reports served as the primary outcome for the lapse risk prediction model. On the remaining 15 items, participants reported any other drugs that they had used, whether they took their MOUD as prescribed in the past 24 hours, and rated the maximum intensity of recent (i.e., in the past 24 hours) experiences of pain, craving, risky situations, stressful events, and pleasant events. They also rated their sleep and how depressed, angry, anxious, relaxed, and happy they have felt in the past 24 hours. Lastly, participants responded to 2 future-facing items that asked about participants’ motivation and confidence to continue to avoid using opioids for non-medical reasons over the next week. The full daily survey is available in the supplement.

### Geolocation Sensing
The STAR app passively recorded participants’ time-stamped geolocations (i.e., latitude and longitude) every 1.5-15 minutes, depending on their movement. We augmented the geolocation data with self-reported subjective context. On each monthly survey participants were asked 6 questions about frequently visited locations (i.e., locations that the participant spent more than 3 minutes on 2 or more times in a month) from the previous month. Participants were asked to describe the type of place, what they typically do there, the general frequency of pleasant and unpleasant experiences at the location, and the extent to which spending time there helps or harms their recovery. The full set of location questions is avilable in the supplement. <!--more detail about monthly survey maybe?  This also included measures collected at enrollment that were expected to change.--><!--KW: lets talk about this, We arent using any of those monthly measures aside from the context questions so I am not sure how much to go into it-->

<!--Add cap on the number of locations that were queried on any survey--><!--cap was 50-->

## Data Analytic Strategy
Data preprocessing, modeling, and Bayesian analyses were done in R using the tidymodels ecosystem [@kuhnTidymodelsCollectionPackages2020; @kuhnTidyposteriorBayesianAnalysis2022; @goodrichRstanarmBayesianApplied2023]. Models were trained and evaluated using high-throughput computing resources provided by the University of Wisconsin Center for High Throughput Computing [@chtc].

### Feature Engineering
Features were calculated using only data collected before the start of each prediction window to ensure our models were making true future predictions. We calculated a total of 297 features from three data sources: 

1. *The prediction window day.* We created one-hot coded features for day of the week for the start of the prediction window.

2. *Demographic individual differences.* For demographics, we created ordinal features for age, education, and income based on predefined response ranges (see @tbl-1 for ranges), an ordinal feature for RUCA code associated with home address (range 1-10), and one-hot coded features for gender (male, not male), race and ethnicity (non-Hispanic White, Hispanic and/or not White), orientation (heterosexual, not heterosexual), and employment (employed, not employed/looking for work, not employed/not looking or able to work).  

3. *Dynamic daily survey and geolocation sensing data.* For both sets of sensing features we calculated two types of features: raw and difference features. Raw features represent the feature value calculated within a given scoring epoch (e.g., the maximum urge rating reported on the daily survey during the 168 hours immediately preceding the start of the prediction window). Difference features capture participant-level changes from their baseline scores. Specifically, we subtracted each participant’s mean score for each feature using all available data prior to the prediction window from the associated raw feature (e.g., the participant’s average urge rating across all prior daily surveys subtracted from the maximum urge rating in the preceding 168 hours).

    For the daily survey, we calculated raw and difference features for the most recent and the min, max, and median responses in the 168 hours preceeding the start of the prediciton window for the 13 5-point likert scale items (items 4-16; pain, urge, risky situation, stressful event, pleasant event, sleep, depressed, angry, anxious, relaxed, happy, abstinence motivation, and abstinence confidence). We also calculated raw and difference rate features based on counts of previous opioid lapses, other drug use, missed MOUD doses (items 1-3), and completed daily surveys in 24 and 168-hour feature scoring epochs (e.g., counts of opioid lapses within the 168 hours preceding the start of a prediction window divided by 168).

    We used two feature scoring epochs (24 and 168 hours before the start of the prediction window) to create proximal and distal geolocation features. Raw geolocation points were cross-checked against known locations with reported subjective context. We used a threshold of 50 meters for matching context to geolocation points. We calculated raw and difference features for sum duration of time out of the home in the evenings (i.e., not at their home between the hours of 7:00pm-4:00am). We calculated raw and difference features for sum duration of time spent at locations according to what they indicated they do at the location (spend time with friends, socialize with new people, religious activities, relax, spend time with family, volunteer, receive mental health care, receive physical health care, receive MOUD treatment, drink alcohol, take classes, work), how pleasant and unpleasant their experiences typically are at the location (Always, Most of the time, Sometimes, Rarely, Never), and how helpful and harmful the location is to their recovery (Extremely, Considerably, Moderately, Mildly, Not at all). We also calculated a raw and difference feature of location variance (i.e., the extent to which a participant's location changes over a feature scoring epoch). 

All features (sets 1-3 above) were included in our full model. We also fit three models with varying ablated sensing features from set 3. Specifically, these models ablated daily survey features, ablated geolocation features, and ablated daily survey and geolocation features combined to assess the incremental predictive value of these features.  

Other feature engineering steps performed during cross-validation included imputing missing values (median imputation for numeric features and mode imputation for nominal features), dummy coding nominal features, normalizing features to have a mean of zero and standard deviation of 1, bringing outlying values (|z-score| > 5) to the fence, and removing zero and near-zero variance features as determined from held-in data. We selected coarse median/mode methods for handling missing data due to the low rates of missing values and computational costs associated with more advanced forms of imputation (e.g., KNN imputation, multiple imputation). A sample feature engineering script (i.e., tidymodels recipe) containing all feature engineering steps is available on our OSF study page.

### Lapse Labels
Prediction windows started at 6:00am in participants' local timezones and ended at 5:59am the next day. This window start time was selected to more closely approximate a typical wake-sleep cycle as opposed to midnight-to-midnight calendar day. For each participant the first prediction window began at 6:00am on their second day of participation and rolled forward day-by-day until their participation ended (i.e., the last prediction window ended at 5:59am on the day of their last recorded daily survey). <!--JJC: day before their last survey?--><!--KW: no it was technically the last day but it was early morning before the last survey was available at 6 am--> Responses from the first daily survey item were used to label each prediction window as lapse or no lapse. For example, if a participant reported a lapse on December 12 from 12:00am-5:59am the prediction window spanning 6:00am on December 11 through 5:59am on December 12 was labeled as a lapse.

### Cross-Validation
We used nested cross-validation for selection and evaluation of the final candidate model configurations. We used 1 repeat of 5-fold cross-validation on the inner loop for model selection and 6 repeats of 5-fold cross-validation on the outer loop for evaluation. Participants were grouped so that all of their data were always in the held-in or held-out fold to avoid bias introduced when predicting a participant’s data from their own data. Folds were stratified so that all folds contained comparable proportions of individuals who lapsed while on study.<!--what it stratified just on lapse vs. no-lapse or something more complicated?  How does that compare to what we do with RISK--><!--KW: stratified on hi/lo performed worse we decided to use yes/no because lapses may be considered a bigger deal and therefore be more homogenous across frequent vs infrequent lapsers-->

### Model Configurations
We initially considered three statistical algorithms that differed in terms of assumptions and bias-variance tradeoff: elastic net, random forest, and XGBoost. Preliminary analyses using simple 6x5 cross-validation suggested that XGBoost was superior (see supplement for initial performance estimates by algorithm). Additionally, we planned to use the Shapley additive explanations (SHAP) method for calculating feature importance which is optimized for XGBoost. Therefore we only considered XGBoost for the final nested cross-validation analyses.

Final candidate model configurations differed across sensible values for key hyperparameters and outcome resampling method (i.e., up-sampling and down-sampling of the outcome at ratios ranging from 5:1 to 1:1). All resampling was exclusively done in the held-in training data (i.e., held-out data were not resampled) to prevent biasing performance estimates [@vandewieleOverlyOptimisticPrediction2021]. All model configurations were fit for the full model and the three feature ablation models (ablated daily survey features, ablated geolocation features, and ablated daily survey and geolocation features combined). 

### Model Evaluation
We evaluated the best full model’s probability predictions across three domains: discrimination, calibration, and overall performance. We follow recommendations for reporting measures and plots to characterize these performance domains [@vancalsterEvaluationPerformanceMeasures2025]. 

#### auROC and Model Comparisons
Our performance metric for model selection and evaluation was the area under the receiver operating characteristic curve (auROC).  auROC is an aggregate measure of discrimination across all possible decision thresholds. Specifically, it represents the probability that the model will assign a higher predicted probability to a randomly selected positive case (lapse) compared to a randomly selected negative case (no lapse). 

We used a Bayesian hierarchical generalized linear model to estimate the posterior distribution and 95% credible intervals (CI) for auROC for the 30 held-out test sets (i.e., held-out data in the outer loop of the nested cross-validation procedure) for our best full and ablated models. We used weakly informative, data-dependent priors to regularize and reduce overfitting. Priors were set as follows: residual standard deviation ~ normal(location=0, scale=exp(2)), intercept (after centering predictors) ~ normal(location=2.3, scale=1.3), the two coefficients for window width contrasts ~ normal (location=0, scale=2.69), and covariance ~ decov(regularization=1, concentration=1, shape=1, scale=1). We set two random intercepts to account for our resampling method: one for the repeat, and another for the fold nested within the repeat. We specified three model contrasts that compared the full model to each of the three ablated models (full vs. ablated daily survey features, full vs. ablated geolocation features, full vs. ablated daily survey and geolocation features combined). auROCs were transformed using the logit function and regressed as a function of model contrast. From the Bayesian model we obtained the posterior distribution for auROC for the full and baseline models. We reported the median posterior probability for auROC and 95% CIs for each model. We then conducted four Bayesian model comparisons to determine the probability that the full model differed systematically in performance compared to the three ablated models.

We performed five dichotomous subgroup analyses to assess the fairness of our model's predictions. Using the same 30 held-out test sets and the same modeling procedure as above, we calculated the median posterior probability and 95% CI for auROC for each model separately by gender (not male vs. male), race/ethnicity (Hispanic and/or non-White vs. non-Hispanic White), income (less than \$25,000 vs. more than \$25,000)<!--We usually refer to this comparison as below poverty but our lowest income group is technically above the federal poverty line ($15,960)-->, sexual orientation (heterosexual vs. not heterosexual), and geographic location (rural vs. urban)^[We followed guidelines from the United States Health Resources and Services Administration and define urban as an area where the primary commuting flow is within a metropolitan core of 50,000 or more people (RUCA code = 1) and rural as anything not urban (RUCA codes 2-10). [@healthresourcesandservicesadministrationHowWeDefine]. We conducted Bayesian group comparisons to assess the likelihood that each model performs differently by group.

#### Calibration and Overall Performance
To further evaluate our model's predictions, we used our inner resampling procedure (1 repeat of 5-fold cross validation) on the full data set to select and fit a single best model configuration for the full model. The final configuration selected represents the most reliable and robust configuration for deployment. 

Calibration is an indicator of how well a model's predicted probabilities match the true observed outcomes. For example, a well-calibrated model that assigns a 30% lapse risk prediction should observe lapses in approximately 30% of such cases. We used Platt scaling to calibrate our final full model's raw probabilities from the 5 held-out folds [@plattProbabilisticOutputsSupport1999]. We provided a calibration plot of these raw and calibrated probabilities. To characterize overall performance we reported Brier scores for the raw and calibrated probabilities. Brier scores are the mean squared difference between the predicted probabilities and observed outcome and range from 0 (perfect accuracy) to 1 (perfect inaccuracy). We also provided histograms of risk probability distributions by true lapse outcome.

### Feature Importance
Feature importance values provide insight into the features that have the most influence on the model's predictions. For every prediction, we can extract feature importance values providing actionable insight into intervenable targets for lapse risk (i.e., for a specific individal at a specific moment). We used the same single 5-fold cross-validation procedure (see Calibration and Overall Performance section) to calculate raw Shapley values for each observation in held-out data [@lundbergUnifiedApproachInterpreting2017]. The magnitude of the raw Shapley value indicates how much the feature score for that observation adjusted the prediction (in log-odds units) relative to the mean prediction across all observations. Positive Shapley values indicate that the feature score increased the prediction for that observation and negative values indicate that the feature score decreased the prediction. In other words, higher Shapley values suggest the feature increases lapse risk and lower values suggest the feature decreases lapse risk. Shapley values are inherently additive. For any observation, Shapley values can be summed to create a total adjustment score for the predicted value. We created feature categories by collapsing features that differed only by scoring epoch and calculation into a single feature category (e.g., Raw features for most recent urge rating, and min, max, and mean urge rating in the 168 hours preceding the start of the prediction window were combined to form a "Urge, Raw" feature category). Raw and difference features were not combined as their relationship to risk were not uniform. We plotted individual Shapley values and feature categories as partial dependence plots to illustrate these feature-risk relationships. 

Feature importance values can also be aggregated across all participants and all observations to provide a relative rank ordering of the most important features. We calculated overall feature importance in two ways. First, we used a traditional approach in which we calculated the mean absolute Shapley value for each feature category across all observations. This approach summarizes overall feature importance by averaging the magnitude of each feature's contribution. However, it can be skewed toward features that exhibit infrequent but very large Shapley values, potentially overstating the importance of features that are strongly associated with the outcome, but only come up in a small subset of observations. The second way we calculated feature importance was by calculating the proportion of observations in which each feature category had the highest Shapley value. This approach summarizes how frequently a feature category is influential across observations (i.e., considering both magnitude and prevalence). We provided a plot of the relative ranking of feature categories by their overall feature importance using these two methods.

# Results

## Participants
We enrolled 330 participants across 47 states in the United States from April 2021 through December 2024. To be considered enrolled in the study, participants were required to be eligible, consent, and complete the first personalized monthly survey where geolocation context were provided.^[405 participants consented to participate in the study and provided at least one daily survey; however, 75 participants dropped out prior to completing the first personalized monthly survey and were therefore not considered fully enrolled in the study.] Of these 330, 14 were excluded for not providing at least 28 days of EMA data with acceptable adherence^[If adherence fell below 33% (roughly 9 surveys in a 28-day period) for a prolonged period of time, participant study end dates were changed to match the start of this adherence drop.], 7 participants were excluded due to evidence of careless responding on daily surveys, and 13 participants were excluded due to having insufficient context data for geolocation points (fewer than two contextualized locations). Our final analysis sample consisted of 296 participants. Participant demographic and OUD characteristics of our final sample is presented in @tbl-1.

{{< embed notebooks/mak_tables.qmd#tbl-1 >}}

## Adherence, Features, and Labels
Mean days on study across participants was 278.32 days (range 30-392 days). 77.7% of participants (230/296) remained on study for at least six months. Daily survey adherence was high. On average participants completed 77.8% of the daily survey prompts (range 40-100%). Participants provided, on average, 263.50 daily geolocation points (range 2.17-871.34). 

The average percentage of missing values across daily survey features was low (mean=0.71%, range 0-1.10%). The average percentage of missing values across geolocation features was higher (mean=12.0%, range 0-15.6%). Across participants we generated a total of 82,156 day-level labels. Thirty-six percent of participants (106/296) reported an opioid lapse while on study (mean=4.93, range 0-117). This resulted in 1.8% of the labels positive for lapse (1,458/82,156 labels). We stratified the data on a variable of whether someone lapsed on study to ensure our imbalanced outcome was evenly split (and roughly equivalent to the sample prevalance) across cross-validation folds.


## auROC and Model Comparisons
The median posterior probability for the best full model was `r sprintf("%.2f", pp_perf$pp_median[1])`, with narrow 95% CI ([`r sprintf("%.2f", pp_perf$pp_lower[1])`, `r sprintf("%.2f", pp_perf$pp_upper[1])`]). To evaluate the incremental predictive value of our dynamic sensing features, we compared the performance of our full model to the performance of three ablated models: `r sprintf("%.2f", pp_perf$pp_median[2])` (ablated daily survey features), `r sprintf("%.2f", pp_perf$pp_median[3])` (ablated geolocation features), and `r sprintf("%.2f", pp_perf$pp_median[4])` (ablated daily survey and geolocation features). There was strong evidence that the full model's performance was better compared to models that ablated the daily survey features and the daily survey and geolocation features combined (probabilities = 1.00). There was no evidence that the full model performed better than a model with geolocation features ablated (probability = 0.34). The median difference in auROC, 95% Bayesian CI, and posterior probability that that the auROC difference was greater than 0 for all ablation contrasts are presented in @tbl-2.

{{< embed notebooks/mak_tables.qmd#tbl-2 >}}

Our fairness subgroup comparisons for the full model revealed strong evidence that performance differed by gender, income, race and ethnicity, sexual orientation, and geographic location (probabilities > 0.97). Notably, our model performed better for individuals with an annual income of less than \$25,000 compared to individuals with an annual income greater than \$25,000, thus favoring the disadvantaged group. While differences in performance estimates exist, this model is likely still clinically meaningful across subgroups, as all subgroups yielded median auROCs between 0.91 - 0.95 (@fig-1). A table of fairness subgroup comparisons is available in the supplement.

{{< embed notebooks/mak_figures.qmd#fig-1 >}}


## Calibration and Overall Performance
The best full model configuration selected with 1 repeat of 5-fold cross-validation used an xgboost statistical algorithm and up-sampled the minority class.^[The best model configuration used 1:5 upsampling of the majority class and the following hyperparameter values: learning rate = .1, tree depth = 3, mtry = 50.] This model produced generally well-calibrated raw probabilities (brier score = `r round(yardstick::brier_class(probs, truth = label, prob_raw)$.estimate, 3)`; left panel of @fig-2). We attempted to improve calibration with Platt scaling and results were comparable (brier score = `r round(yardstick::brier_class(probs, truth = label, prob_logi)$.estimate, 3)`). Histograms of raw risk probability distributions separately by true lapse outcome are presented in the right panel of @fig-2.

{{< embed notebooks/mak_figures.qmd#fig-2 >}}


## Feature Importance
We aggregated individual Shapley values across all participants and all observations to provide a relative rank ordering of the most important features. A traditional mean absolute Shapley value approach revealed the most important feature (i.e., largest magnitude of change in log-odds) was differences in past opioid use. These feature was nearly two-fold more important than the next most important feature, raw urge ratings. @fig-3 displays the top 30 (out of 186) feature categories, as defined by the 30 largest absolute mean shapley values. In the supplement, we provide full figures of all possible feature categories.

A second approach where we calculated the proportion of observations in which each feature category had the highest Shapley value (i.e., largest magnitude and prevalence), revealed the most important feature to be raw urge ratings, followed by raw abstinence confidence ratings. Differences in past opioid use was the third most important feature by this method, suggesting that while it has a strong relationship with lapse risk, it is not as prevalent across observations as other features. Notably, in this approach several additional comparably important features emerged, including differences in past pleasant experiences, differences in past stimulant use, and differences in time spent in helpful locations.


{{< embed notebooks/mak_figures.qmd#fig-3 >}} 


To understand the direction in which these feature categories adjusted the lapse risk predictions, we plotted Shapley-feature value partial dependence plots for the top 30 feature categories (@fig-4). Differenes in past opioid use lowered lapse risk probability for participants who did not lapse on study (i.e., a feature score of 0). Lapse probability dramatically increased when participants had increased reported opioid use over the past 24 and 168 hours. Unsurprisingly, raw urge and abstinence confidence ratings had linear relationships to lapse risk, with higher urge ratings increasing lapse risk probability and higher abstinence confidence decreasing lapse risk probability. There was a more nuanced finding for stimulant use and opioid lapse risk probability. Raw rate counts of stimulant use increased lapse risk; however, participants were at highest risk when recent stimulant use decreased (i.e., Stimulant Use, Diff). 

{{< embed notebooks/mak_figures.qmd#fig-4 >}} 


# Discussion
Our full model demonstrated that it is possible to predict future next-day lapses back to opioid use with high accuracy using smartphone sensing methods (auROC = 0.94). Our model's predictions were well-calibrated, meaning that our probabilities closely matched true observed lapse rates. This is exciting given that our goal was to build a model that could provide insight into lapse risk. 

Ablation model comparisons revealed that daily surveys alone captured nearly all of this predictive signal (auROC = 0.94). To our knowledge, no other published substance use studies have collected daily survey data from participants continuously over the course of one year. Survey adherence rates in our sample were comparable to those observed in other clinical populations, suggesting that self‑report surveys are a feasible and scalable sensing method for long‑term monitoring in this population.

When daily surveys were ablated from the model, predictive performance dropped substantially (auROC = 0.63). Although this performance remained above chance and exceeded that of a demographics‑only model (with both geolocation and daily surveys ablated; auROC = 0.55), it indicates that geolocation features captured only modest independent predictive signal. Moreover, given that ablating geolocation features did not result in any drop in performance, this signal likely overlaps with information already captured with the daily surveys. It is possible that the relatively low predictive value of geolocation sensing in this study was due to methodological limitations. 

Although geolocation data can, in principle, be collected continuously moment‑by‑moment, in practice these data are difficult to collect reliably. In our study, geolocation features had substantially higher rates of missingness compared to daily surveys. Consequently, approximately 12% of geolocation features were imputed using median values derived from other individuals in the training dataset. Median values are by definition near the center of the feature distribution. These values are common and have limited influence on model predictions (i.e., low leverage). This was a purposeful decision in our design to ensure that missing data would not systematically influence predictions in either direction. However, this conservative approach likely contributed to reduced predictive performance of geolocation features, as imputations that minimize influence also limit the ability of those features to contribute risk‑relevant signal. Lastly, these median imputations are also not person-specific and as a result may not accurately represent typical values for the individual whose data are being imputed. As geolocation sensing methods become more robust and missingness is reduced, these features may become more powerful for lapse prediction. 

A second limitation of our sensing method, was that we relied on known locations with self-reported context. While this method provides meaningful contextual information, it is limited in its ability to capture the full range of locations participants visit (without substantially increasing participant burden). Passive methods for contextualizing location could address this limitation by providing risk-relevant contextual information across all locations. For example, latitude and longitude coordinates could be contextualized using publicly available datasets, such as alcohol outlet density, area deprivation index, and Narcotics Annonymous meeting times and locations. Increasing the number of locations would allow for potentially more variance in feature distributions within and between individuals. 

To summarize, if the goal is prediction, geolocation sensing features are not necessary as they do not offer any unique incremental predictive value. However, if the goal is to have a more nuanced understanding of lapse risk across a more diverse array of risk features than geolocation is helpful. Adding geolocation features did not hurt model performance, and more data sources provides more opportunities for identifying intervenable targets specific to a person and moment in time. 

We were excited to see that fairness discrepancies in model performance were minimal. In all subgroups, our model had a median auROC above 0.90, which is generally considered to be a benchmark of excellent performance. Nevertheless, differences of 0.02 - 0.03 (favoring the advantaged group) were present in race and ethnicity, sexual orientation, and geographic location comparisons. These group comparisons were the most imbalanced, with 19-29% of participants in the disadvantaged groups. Our model may perform better for these groups with greater representation in the training data. Future research into identifying additional risk factors for lapse that are more prevalent in these groups may also help to reduce these discrepancies. 

Age may be another important dimension for evaluating model fairness. Older adults (65+ years) are less likely to receive substance use disorder treatment and often report lower levels of social interaction and support than younger adults. They may also be less comfortable with, or less able to provide, smartphone sensing data at the level of adherence needed for accurate prediction. We did not explicitly evaluate model fairness for this subgroup because we did not have the representation in our sample. We encourage researchers to perform this analysis in future studies.


- Top features

- paid, and withdrawn for adherence, stillk nearly 78% of paprticipnat rmeainf on study for 6 months with this exckludion criteia







<!-- Time series models -->
<!-- - Participants provided data for up to 12 months. This extended window of recovery (12 months vs. 3 months) is critical for evaluating the value of an algorithm intended for ongoing continuing care support and understanding how lapse risk evolves as people progress in their recovery (i.e., past 3 months). Unfortunately, our ability to address explanatory questions about the time course of lapse risk, and how individuals might cluster on different recovery trajectories is limited with traditional machine learning methods. These methods do not capture the repeated nature of sensing data. Each lapse prediction is treated as a new independent observation. We can account for the repeated observations in our sensing data by engineering features that capture individual changes over time to produce unbiased and precise estimates of predictive performance. However, more traditional time series models are better suited for understanding the temporal dynamics of lapse risk over long periods of recovery. -->


<!-- - Decision not include misclassification cost analyses: acknowledge that discrimination and calibration don't equate to clinical utilility. Decision analysis tools, such as net benefit curves could be used to quantify clinical benefit at relevant probability thresholds. Our model is designed to not be used to make decisions about whether or not to treat but to provide model feedback to individuals each day to help them monitor their risk for lapse. Therefore the decision has already been made to always treat. Should these models be used to inform when to deploy more cost-intensive interventions (e.g., communicating risk level to a therapist to initiate contact) these analyses will be important next steps. -->

<!-- - Although, classification and clinical utility are two other important domains for evaluating a model intended to make or inform a decision (e.g., whether to send a support message to an individual). In applications of our model there would be no decision to be made. Every day an individual would receive a message regardless of their lapse risk, equivalent to a treat all condition. Therefore, we have constrained our evaluation to focus on the probability estimates for evaluating performance.  -->

<!-- - Optimal thresholds depend on the setting, outcome prevalence, and the relative costs of misclassification, and should be addressed separately from discrimination evaluation (e.g., with a decision curve analysis). -->





# References
::: {#refs}
:::
